Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/03/2023
var
x,n,soma:inteiro
inicio

para n<- ate 10 faca
 escreval("Entre com o valor")
 leia(x)
 soma<-soma+x
fimpara
escreval("Resultado", soma)
fimalgoritmo